/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.3.3/samples
 */

plugins {
    java
    kotlin("jvm") version "1.6.10"
    application
}

group = "at.stnwtr"
version = "1.0.0"

repositories {
    mavenCentral()
}

application.mainClass.set("at.stnwtr.asboet.LauncherKt")
