/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.3.3/samples
 */

plugins {
    java
    kotlin("jvm") version "1.6.10"
    application
}

group = "at.stnwtr"
version = "1.0.0"

repositories {
    mavenCentral()
}

dependencies {
    // Webserver
    implementation("io.javalin:javalin:4.4.0")

    // Logging
    implementation("org.slf4j:slf4j-simple:1.7.36")

    // Json mapper
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.13.2")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.2")

    // HTML parser
    implementation("org.jsoup:jsoup:1.14.3")
}

application.mainClass.set("at.stnwtr.asboet.LauncherKt")
